name: "Shell Commands"

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: "echo a string"
        run: echo "Hello world"
      - name: "multiline script"
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          print("Hello world")
        shell: python
  run-windows-commands:
    runs-on: windows-latest
    needs: [run-shell-command] # Requirement when running this job
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash